### PR TITLE
First collaboration UniPD-NIST on qd-realization

### PR DESCRIPTION
**Pull request by mattia-lecci**
This pull requests adds compatibility for multiple platforms (Windows, Mac OS, Linux), reorders folder structure, cleans some code, and improves performance.

### CODE REVIEW

**Comment by mattia-lecci** [comment]
@anrg-nist commenting on 302a99f
Yes, you are indeed correct. For this reason in commit 70790be09e9ba2309ca3f219ee0d316f09ae8211 and 302a99fe954679735a5c242c525711a3e71769b1 I removed some more string definitions, exactly for retro-compatibility.
Take a look at commit 70790be09e9ba2309ca3f219ee0d316f09ae8211, for example, where I solve exactly the problem you mentioned by creating a cell array of char arrays rather than a matrix of strings. Commit 9967cf5a9895923b7f791d9cdece63dc04ba533f is where I removed the necessity of such a variable at once, writing directly to the TXT output file and significantly improving performance.

**Comment by mattia-lecci** [comment]
> A detailed explanation is preferred for deletion of each file. How were the files incorporated into other functions or were they never used or modifications were made to code that rendered these functions vestigial?

Here are the reasons why I deleted each one of these functions in commit 8776cae:
* `Calc_angle` and `Calculate_Ex_Ey` were only called by `Polarization` and some commented code in `singleMultipathGenerator`
* `Fresnel` was only called by `Polarization`
* As `Polarization` is not part of this release, it was already commented out in `singleMultipathGenerator`. This created the chain reaction that allowed me to delete more unused functions.
* `SameSide` and `getPlaneEquation` were simply never called
* `StringOutputGenerator` was replaced by `getQdFilesIds`, `writeQdFileOutput`, and `closeQdFilesIds` as previously discussed

As I already said, they can be later restored if we find them useful for a future release.

**Comment by mattia-lecci** [comment]
> These lines were omitted.
> % QD plot(f2) parameters
> if dod(1) == 0
> dod(1) = 0;
> end
> An explanation is needed to describe on how these omitted lines were incorporated into the code.
> The tests ran good and the results are expected. This includes the corner when Tx = (1, 3, 2) and Rx = (1, 12.4, 1.4).

These lines were never incorporated in the code as they do not do anything. Checking if a float is _exactly_ equal to zero and, if so, then setting it to zero again is pointless. Maybe you wanted to check for numerical error? In that case you should have used instead
```matlab
if dod(1) < tol
    dod(1) = 0;
end
```
With `tol` being a small number. Sometimes `n * eps(x)` is used, in this case replacing `x = dod(1)` and `n = 32`. [Here](https://matlabgeeks.com/tips-tutorials/floating-point-comparisons-in-matlab/) a reference for this. As you can see, dealing with numerical errors, especially when they cumulate, can be really hard. Let me know what were your intentions there and we can try to figure out the best way to fix the code.

**Comment by mattia-lecci** [comment]
> As mentioned in the previous commit. I like this addition of a default scenario. I was wondering if there is a way to avoid giving the file name in the console.

Indeed there is. There are actually multiple ways to do this. For example, as I find it annoying to input the scenario name every time, I usually remove the `input` command when defining `scenarioNameStr`, writing directly a path (e.g., `''`, in order to use `ScenarioTest`). This is the way to do it changing directly the code. If, instead, you want to really automate the code, the `main` script should be transformed into a function, accepting as inputs, for example, the `scenarioNameStr`. In this way you can decide externally where the scenario is going to be read and computed, e.g., from a BASH script. We can add this in a later release if you're interested.

**Comment by mattia-lecci** [comment]
> I had issue with gitignore when i used your code.
> Below is the error in Matlab
> image
> And when I go to input folder I see this
> image
> 
> Please let me know if this has to do with gitignore?

From the picture of your empty folder I think you are using a future commit, meaning after the folder structure change (I can see the src folder from the picture). If this is the case, the scenarios are now in the `examples` folder. Try inputting `examples/Indoor1`, instead. Let me know if it works.

**Review by anrg-nist — APPROVED** [review]

**Pull request merged**
